export function sanitizeTextForSpeech(text: string): string {
  return text
    .replace(/\r\n?/g, "\n")
    .replace(/```[a-z0-9_-]*\n?([\s\S]*?)```/gi, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, "$1")
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1")
    .replace(/https?:\/\/\S+/gi, "")
    .replace(/<[^>]+>/g, " ")
    .replace(/^\s*([-*_])(?:\s*\1){2,}\s*$/gm, "")
    .replace(/^\s{0,3}#{1,6}\s+(.+?)\s*#*\s*$/gm, "$1.\n")
    .replace(/^\s*>\s?(.*)$/gm, "$1\n")
    .replace(/^\s*[-*+]\s+(.+)$/gm, "$1.\n")
    .replace(/^\s*\d+[.)]\s+(.+)$/gm, "$1.\n")
    .replace(/(\*\*|__)(.*?)\1/g, "$2")
    .replace(/(?<!\w)([*_~])([^*_\n~]+)\1(?!\w)/g, "$2")
    .replace(/[*_~#|]+/g, " ")
    .replace(/\s+-\s+/g, ", ")
    .replace(/\s*[\u2013\u2014]\s*/g, ", ")
    .replace(/&/g, " and ")
    .replace(/\p{Extended_Pictographic}/gu, " ")
    .replace(/\s*\.\s*\./g, ".")
    .replace(/([.!?])\s*\1+/g, "$1")
    .replace(/\n+/g, " ")
    .replace(/\s+([,.;:!?])/g, "$1")
    .replace(/([,.;:!?])(?=\S)/g, "$1 ")
    .replace(/\s+/g, " ")
    .trim();
}
